name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Upload DEB
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debian package
      uses: singingwolfboy/build-dpkg-buster@v1
      with:
          args: --unsigned-source --unsigned-changes
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftp-upload.net
        user: fl0te_27750748
        password: gd2cvycn
        localDir: ${{ steps.build.outputs.filename }}
        remoteDir: repos.hostfree2021.ml/htdocs/debian/buster/pool/main/n/nginx/${{ steps.build.outputs.filename }}
